/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.leqili.printprimenumbers;


public class App {


    public boolean isPrime(int num){
        for(int i = 2; i < num; i++){
            if (num % i == 0){
                return false;
                }
        }
               
        return true;
    }

    

    


    

    public static void main(String[] args) {
        App myApp = new App();
        for(int num1 = 2; num1 <= 200; num1++){
            if(myApp.isPrime(num1)){
                System.out.println(num1);
            }
        }
    }
}
